@startuml
skinparam classAttributeIconSize 0
' to use standard notation for public, protected, private

class MainCompoundAndSimple {
+ {static} main(String[] args)
}

class CompoundInterest {
- principal : double
- rate : double
+ CompoundInterest(principal : double, rate : double)
+ simulate(numYears : int)
}

class SimpleInterest {
- principal : double
- rate : double
+ SimpleInterest(principal : double, rate : double)
+ simulate(numYears : int)
}

' position classes
MainCompoundAndSimple -[hidden]down-> SimpleInterest
SimpleInterest -[hidden]right-> CompoundInterest
@enduml