@startuml
skinparam classAttributeIconSize 0

class MainCompoundAndSimple2 {
+ {static} main(String[] args)
}
abstract class Interest {
# principal : double
# rate : double
**# valueOfInvestment : double**
+ Interest(principal : double, rate : double)
**+ simulate(numYears : int)**
**# {abstract} applyRate() : double**
}
class CompoundInterest2 extends Interest {
+ CompoundInterest2(principal : double, rate : double)
**# applyRate() : double**
}
class SimpleInterest2 extends Interest {
+ SimpleInterest2(principal : double, rate : double)
**# applyRate() : double**
}
note bottom of SimpleInterest2
principal * rate / 100.0
end note
note bottom of CompoundInterest2
valueOfInvestment * rate / 100.0
end note
' position classes
MainCompoundAndSimple2 -[hidden]down-> SimpleInterest2
SimpleInterest2 -[hidden]right-> CompoundInterest2
@enduml